name: Puppeteer Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
      PUPPETEER_CACHE_DIR: .puppeteer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run Puppeteer smoke test
        run: npm run test:puppeteer
